[web]
web-server ansible_host=13.53.51.59
[common]
common-server ansible_host=16.171.173.179
[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/ubuntu/keys/ansible-demo
ansible_host_key_checking=false


